// 完整用户可见文案（如"XX音频"这类拼接）只能经 lib/ui/ 下的 helper 组装；
// code 规整（normalizeLanguageCode 等）、语言名查表（languageName/subtitleLabel）
// 允许模型/store 等层直接 import 调用，但模型层禁止拼出用户可见的完整文案。
class MediaLanguageMapper {
  MediaLanguageMapper._();

  static final Map<String, String> _languageNameMap = {
    'ara': '\u963f\u62c9\u4f2f\u8bed',
    'ar': '\u963f\u62c9\u4f2f\u8bed',
    'bul': '\u4fdd\u52a0\u5229\u4e9a\u8bed',
    'bg': '\u4fdd\u52a0\u5229\u4e9a\u8bed',
    'cat': '\u52a0\u6cf0\u7f57\u5c3c\u4e9a\u8bed',
    'ca': '\u52a0\u6cf0\u7f57\u5c3c\u4e9a\u8bed',
    'ces': '\u6377\u514b\u8bed',
    'cze': '\u6377\u514b\u8bed',
    'cs': '\u6377\u514b\u8bed',
    'jpn': '\u65e5\u8bed',
    'ja': '\u65e5\u8bed',
    'jp': '\u65e5\u8bed',
    'chi': '\u4e2d\u6587',
    'zho': '\u4e2d\u6587',
    'zh': '\u4e2d\u6587',
    'cmn': '\u4e2d\u6587',
    'eng': '\u82f1\u8bed',
    'en': '\u82f1\u8bed',
    'dan': '\u4e39\u9ea6\u8bed',
    'da': '\u4e39\u9ea6\u8bed',
    'nld': '\u8377\u5170\u8bed',
    'dut': '\u8377\u5170\u8bed',
    'nl': '\u8377\u5170\u8bed',
    'ell': '\u5e0c\u814a\u8bed',
    'gre': '\u5e0c\u814a\u8bed',
    'el': '\u5e0c\u814a\u8bed',
    'est': '\u7231\u6c99\u5c3c\u4e9a\u8bed',
    'et': '\u7231\u6c99\u5c3c\u4e9a\u8bed',
    'fin': '\u82ac\u5170\u8bed',
    'fi': '\u82ac\u5170\u8bed',
    'fra': '\u6cd5\u8bed',
    'fre': '\u6cd5\u8bed',
    'fr': '\u6cd5\u8bed',
    'heb': '\u5e0c\u4f2f\u6765\u8bed',
    'he': '\u5e0c\u4f2f\u6765\u8bed',
    'hin': '\u5370\u5730\u8bed',
    'hi': '\u5370\u5730\u8bed',
    'hrv': '\u514b\u7f57\u5730\u4e9a\u8bed',
    'hr': '\u514b\u7f57\u5730\u4e9a\u8bed',
    'hun': '\u5308\u7259\u5229\u8bed',
    'hu': '\u5308\u7259\u5229\u8bed',
    'ind': '\u5370\u5c3c\u8bed',
    'id': '\u5370\u5c3c\u8bed',
    'ita': '\u610f\u5927\u5229\u8bed',
    'it': '\u610f\u5927\u5229\u8bed',
    'kor': '\u97e9\u8bed',
    'ko': '\u97e9\u8bed',
    'lav': '\u62c9\u8131\u7ef4\u4e9a\u8bed',
    'lv': '\u62c9\u8131\u7ef4\u4e9a\u8bed',
    'lit': '\u7acb\u9676\u5b9b\u8bed',
    'lt': '\u7acb\u9676\u5b9b\u8bed',
    'msa': '\u9a6c\u6765\u8bed',
    'may': '\u9a6c\u6765\u8bed',
    'ms': '\u9a6c\u6765\u8bed',
    'nob': '\u632a\u5a01\u8bed',
    'nno': '\u632a\u5a01\u8bed',
    'nor': '\u632a\u5a01\u8bed',
    'nb': '\u632a\u5a01\u8bed',
    'nn': '\u632a\u5a01\u8bed',
    'no': '\u632a\u5a01\u8bed',
    'pol': '\u6ce2\u5170\u8bed',
    'pl': '\u6ce2\u5170\u8bed',
    'por': '\u8461\u8404\u7259\u8bed',
    'pt': '\u8461\u8404\u7259\u8bed',
    'ron': '\u7f57\u9a6c\u5c3c\u4e9a\u8bed',
    'rum': '\u7f57\u9a6c\u5c3c\u4e9a\u8bed',
    'ro': '\u7f57\u9a6c\u5c3c\u4e9a\u8bed',
    'rus': '\u4fc4\u8bed',
    'ru': '\u4fc4\u8bed',
    'slk': '\u65af\u6d1b\u4f10\u514b\u8bed',
    'slo': '\u65af\u6d1b\u4f10\u514b\u8bed',
    'sk': '\u65af\u6d1b\u4f10\u514b\u8bed',
    'slv': '\u65af\u6d1b\u6587\u5c3c\u4e9a\u8bed',
    'sl': '\u65af\u6d1b\u6587\u5c3c\u4e9a\u8bed',
    'spa': '\u897f\u73ed\u7259\u8bed',
    'es': '\u897f\u73ed\u7259\u8bed',
    'srp': '\u585e\u5c14\u7ef4\u4e9a\u8bed',
    'sr': '\u585e\u5c14\u7ef4\u4e9a\u8bed',
    'swe': '\u745e\u5178\u8bed',
    'sv': '\u745e\u5178\u8bed',
    'tha': '\u6cf0\u8bed',
    'th': '\u6cf0\u8bed',
    'tur': '\u571f\u8033\u5176\u8bed',
    'tr': '\u571f\u8033\u5176\u8bed',
    'ukr': '\u4e4c\u514b\u5170\u8bed',
    'uk': '\u4e4c\u514b\u5170\u8bed',
    'vie': '\u8d8a\u5357\u8bed',
    'vi': '\u8d8a\u5357\u8bed',
    'deu': '\u5fb7\u8bed',
    'ger': '\u5fb7\u8bed',
    'de': '\u5fb7\u8bed',
    'afr': '南非荷兰语',
    'af': '南非荷兰语',
    'sqi': '阿尔巴尼亚语',
    'alb': '阿尔巴尼亚语',
    'sq': '阿尔巴尼亚语',
    'hye': '亚美尼亚语',
    'arm': '亚美尼亚语',
    'hy': '亚美尼亚语',
    'aze': '阿塞拜疆语',
    'az': '阿塞拜疆语',
    'eus': '巴斯克语',
    'baq': '巴斯克语',
    'eu': '巴斯克语',
    'ben': '孟加拉语',
    'bn': '孟加拉语',
    'bos': '波斯尼亚语',
    'bs': '波斯尼亚语',
    'mya': '缅甸语',
    'bur': '缅甸语',
    'my': '缅甸语',
    'fil': '菲律宾语',
    'tgl': '菲律宾语',
    'tl': '菲律宾语',
    'kat': '格鲁吉亚语',
    'geo': '格鲁吉亚语',
    'ka': '格鲁吉亚语',
    'isl': '冰岛语',
    'ice': '冰岛语',
    'is': '冰岛语',
    'gle': '爱尔兰语',
    'ga': '爱尔兰语',
    'kan': '卡纳达语',
    'kn': '卡纳达语',
    'kaz': '哈萨克语',
    'kk': '哈萨克语',
    'khm': '高棉语',
    'km': '高棉语',
    'lao': '老挝语',
    'lo': '老挝语',
    'mkd': '马其顿语',
    'mac': '马其顿语',
    'mk': '马其顿语',
    'mal': '马拉雅拉姆语',
    'ml': '马拉雅拉姆语',
    'mon': '蒙古语',
    'mn': '蒙古语',
    'nep': '尼泊尔语',
    'ne': '尼泊尔语',
    'fas': '波斯语',
    'per': '波斯语',
    'fa': '波斯语',
    'pan': '旁遮普语',
    'pa': '旁遮普语',
    'tam': '泰米尔语',
    'ta': '泰米尔语',
    'tel': '泰卢固语',
    'te': '泰卢固语',
    'urd': '乌尔都语',
    'ur': '乌尔都语',
    'cym': '威尔士语',
    'wel': '威尔士语',
    'cy': '威尔士语',
    'bel': '白俄罗斯语',
    'be': '白俄罗斯语',
    'swa': '斯瓦希里语',
    'sw': '斯瓦希里语',
    'uzb': '乌兹别克语',
    'uz': '乌兹别克语',
    'sin': '僧伽罗语',
    'si': '僧伽罗语',
    'mar': '马拉地语',
    'mr': '马拉地语',
    'guj': '古吉拉特语',
    'gu': '古吉拉特语',
    'kur': '库尔德语',
    'ku': '库尔德语',
    'amh': '阿姆哈拉语',
    'am': '阿姆哈拉语',
    'lat': '拉丁语',
    'la': '拉丁语',
    'glg': '加利西亚语',
    'gl': '加利西亚语',
    'mul': '\u591a\u79cd\u8bed\u8a00',
    'multi': '\u591a\u79cd\u8bed\u8a00',
  };

  static final Map<String, String> _languageAliasToCode = {
    'arabic': 'ara',
    'ara': 'ara',
    'ar': 'ara',
    '\u963f\u62c9\u4f2f\u8bed': 'ara',
    'bulgarian': 'bul',
    'bul': 'bul',
    'bg': 'bul',
    '\u4fdd\u52a0\u5229\u4e9a\u8bed': 'bul',
    'catalan': 'cat',
    'cat': 'cat',
    'ca': 'cat',
    '\u52a0\u6cf0\u7f57\u5c3c\u4e9a\u8bed': 'cat',
    'czech': 'ces',
    'ces': 'ces',
    'cze': 'ces',
    'cs': 'ces',
    '\u6377\u514b\u8bed': 'ces',
    'danish': 'dan',
    'dan': 'dan',
    'da': 'dan',
    '\u4e39\u9ea6\u8bed': 'dan',
    'dutch': 'nld',
    'nld': 'nld',
    'dut': 'nld',
    'nl': 'nld',
    '\u8377\u5170\u8bed': 'nld',
    'english': 'eng',
    'eng': 'eng',
    'en': 'eng',
    '\u82f1\u8bed': 'eng',
    '\u82f1\u6587': 'eng',
    'estonian': 'est',
    'est': 'est',
    'et': 'est',
    '\u7231\u6c99\u5c3c\u4e9a\u8bed': 'est',
    'finnish': 'fin',
    'fin': 'fin',
    'fi': 'fin',
    '\u82ac\u5170\u8bed': 'fin',
    'french': 'fra',
    'fra': 'fra',
    'fre': 'fra',
    'fr': 'fra',
    '\u6cd5\u8bed': 'fra',
    'german': 'deu',
    'deu': 'deu',
    'ger': 'deu',
    'de': 'deu',
    '\u5fb7\u8bed': 'deu',
    'greek': 'ell',
    'ell': 'ell',
    'gre': 'ell',
    'el': 'ell',
    '\u5e0c\u814a\u8bed': 'ell',
    'hebrew': 'heb',
    'heb': 'heb',
    'he': 'heb',
    '\u5e0c\u4f2f\u6765\u8bed': 'heb',
    'hindi': 'hin',
    'hin': 'hin',
    'hi': 'hin',
    '\u5370\u5730\u8bed': 'hin',
    'croatian': 'hrv',
    'hrv': 'hrv',
    'hr': 'hrv',
    '\u514b\u7f57\u5730\u4e9a\u8bed': 'hrv',
    'hungarian': 'hun',
    'hun': 'hun',
    'hu': 'hun',
    '\u5308\u7259\u5229\u8bed': 'hun',
    'indonesian': 'ind',
    'ind': 'ind',
    'id': 'ind',
    '\u5370\u5c3c\u8bed': 'ind',
    'italian': 'ita',
    'ita': 'ita',
    'it': 'ita',
    '\u610f\u5927\u5229\u8bed': 'ita',
    'japanese': 'jpn',
    'jpn': 'jpn',
    'ja': 'jpn',
    'jp': 'jpn',
    '\u65e5\u8bed': 'jpn',
    '\u65e5\u6587': 'jpn',
    '\u65e5\u672c\u8bed': 'jpn',
    'korean': 'kor',
    'kor': 'kor',
    'ko': 'kor',
    '\u97e9\u8bed': 'kor',
    '\u97e9\u6587': 'kor',
    '\u671d\u9c9c\u8bed': 'kor',
    '\u671d\u9c9c\u6587': 'kor',
    'latvian': 'lav',
    'lav': 'lav',
    'lv': 'lav',
    '\u62c9\u8131\u7ef4\u4e9a\u8bed': 'lav',
    'lithuanian': 'lit',
    'lit': 'lit',
    'lt': 'lit',
    '\u7acb\u9676\u5b9b\u8bed': 'lit',
    'malay': 'msa',
    'msa': 'msa',
    'may': 'msa',
    'ms': 'msa',
    '\u9a6c\u6765\u8bed': 'msa',
    'norwegian': 'nor',
    'nor': 'nor',
    'nob': 'nor',
    'nno': 'nor',
    'nb': 'nor',
    'nn': 'nor',
    'no': 'nor',
    '\u632a\u5a01\u8bed': 'nor',
    'polish': 'pol',
    'pol': 'pol',
    'pl': 'pol',
    '\u6ce2\u5170\u8bed': 'pol',
    'portuguese': 'por',
    'por': 'por',
    'pt': 'por',
    '\u8461\u8404\u7259\u8bed': 'por',
    'romanian': 'ron',
    'ron': 'ron',
    'rum': 'ron',
    'ro': 'ron',
    '\u7f57\u9a6c\u5c3c\u4e9a\u8bed': 'ron',
    'russian': 'rus',
    'rus': 'rus',
    'ru': 'rus',
    '\u4fc4\u8bed': 'rus',
    'serbian': 'srp',
    'srp': 'srp',
    'sr': 'srp',
    '\u585e\u5c14\u7ef4\u4e9a\u8bed': 'srp',
    'slovak': 'slk',
    'slk': 'slk',
    'slo': 'slk',
    'sk': 'slk',
    '\u65af\u6d1b\u4f10\u514b\u8bed': 'slk',
    'slovenian': 'slv',
    'slv': 'slv',
    'sl': 'slv',
    '\u65af\u6d1b\u6587\u5c3c\u4e9a\u8bed': 'slv',
    'spanish': 'spa',
    'spa': 'spa',
    'es': 'spa',
    '\u897f\u73ed\u7259\u8bed': 'spa',
    'swedish': 'swe',
    'swe': 'swe',
    'sv': 'swe',
    '\u745e\u5178\u8bed': 'swe',
    'thai': 'tha',
    'tha': 'tha',
    'th': 'tha',
    '\u6cf0\u8bed': 'tha',
    'turkish': 'tur',
    'tur': 'tur',
    'tr': 'tur',
    '\u571f\u8033\u5176\u8bed': 'tur',
    'ukrainian': 'ukr',
    'ukr': 'ukr',
    'uk': 'ukr',
    '\u4e4c\u514b\u5170\u8bed': 'ukr',
    'vietnamese': 'vie',
    'vie': 'vie',
    'vi': 'vie',
    '\u8d8a\u5357\u8bed': 'vie',
    'chinese': 'zho',
    'chi': 'zho',
    'zho': 'zho',
    'zh': 'zho',
    'cmn': 'zho',
    '\u4e2d\u6587': 'zho',
    '\u7b80\u4f53\u4e2d\u6587': 'zho',
    '\u7b80\u4e2d': 'zho',
    '\u7b80\u4f53': 'zho',
    '\u7e41\u4f53\u4e2d\u6587': 'zho',
    '\u7e41\u4e2d': 'zho',
    '\u7e41\u4f53': 'zho',
    'traditional chinese': 'zho',
    'simplified chinese': 'zho',
    'trad': 'zho',
    'traditional': 'zho',
    'simp': 'zho',
    'simplified': 'zho',
    'cht': 'zho',
    'chs': 'zho',
    'afrikaans': 'afr',
    'afr': 'afr',
    'af': 'afr',
    '南非荷兰语': 'afr',
    'albanian': 'sqi',
    'sqi': 'sqi',
    'alb': 'sqi',
    'sq': 'sqi',
    '阿尔巴尼亚语': 'sqi',
    'armenian': 'hye',
    'hye': 'hye',
    'arm': 'hye',
    'hy': 'hye',
    '亚美尼亚语': 'hye',
    'azerbaijani': 'aze',
    'aze': 'aze',
    'az': 'aze',
    '阿塞拜疆语': 'aze',
    'basque': 'eus',
    'eus': 'eus',
    'baq': 'eus',
    'eu': 'eus',
    '巴斯克语': 'eus',
    'bengali': 'ben',
    'bangla': 'ben',
    'ben': 'ben',
    'bn': 'ben',
    '孟加拉语': 'ben',
    'bosnian': 'bos',
    'bos': 'bos',
    'bs': 'bos',
    '波斯尼亚语': 'bos',
    'burmese': 'mya',
    'myanmar': 'mya',
    'mya': 'mya',
    'bur': 'mya',
    'my': 'mya',
    '缅甸语': 'mya',
    'filipino': 'fil',
    'tagalog': 'fil',
    'fil': 'fil',
    'tgl': 'fil',
    'tl': 'fil',
    '菲律宾语': 'fil',
    'georgian': 'kat',
    'kat': 'kat',
    'geo': 'kat',
    'ka': 'kat',
    '格鲁吉亚语': 'kat',
    'icelandic': 'isl',
    'isl': 'isl',
    'ice': 'isl',
    'is': 'isl',
    '冰岛语': 'isl',
    'irish': 'gle',
    'gle': 'gle',
    'ga': 'gle',
    '爱尔兰语': 'gle',
    'kannada': 'kan',
    'kan': 'kan',
    'kn': 'kan',
    '卡纳达语': 'kan',
    'kazakh': 'kaz',
    'kaz': 'kaz',
    'kk': 'kaz',
    '哈萨克语': 'kaz',
    'khmer': 'khm',
    'cambodian': 'khm',
    'khm': 'khm',
    'km': 'khm',
    '高棉语': 'khm',
    'lao': 'lao',
    'laotian': 'lao',
    'lo': 'lao',
    '老挝语': 'lao',
    'macedonian': 'mkd',
    'mkd': 'mkd',
    'mac': 'mkd',
    'mk': 'mkd',
    '马其顿语': 'mkd',
    'malayalam': 'mal',
    'mal': 'mal',
    'ml': 'mal',
    '马拉雅拉姆语': 'mal',
    'mongolian': 'mon',
    'mon': 'mon',
    'mn': 'mon',
    '蒙古语': 'mon',
    'nepali': 'nep',
    'nep': 'nep',
    'ne': 'nep',
    '尼泊尔语': 'nep',
    'persian': 'fas',
    'farsi': 'fas',
    'fas': 'fas',
    'per': 'fas',
    'fa': 'fas',
    '波斯语': 'fas',
    'punjabi': 'pan',
    'panjabi': 'pan',
    'pan': 'pan',
    'pa': 'pan',
    '旁遮普语': 'pan',
    'tamil': 'tam',
    'tam': 'tam',
    'ta': 'tam',
    '泰米尔语': 'tam',
    'telugu': 'tel',
    'tel': 'tel',
    'te': 'tel',
    '泰卢固语': 'tel',
    'urdu': 'urd',
    'urd': 'urd',
    'ur': 'urd',
    '乌尔都语': 'urd',
    'welsh': 'cym',
    'cym': 'cym',
    'wel': 'cym',
    'cy': 'cym',
    '威尔士语': 'cym',
    'belarusian': 'bel',
    'byelorussian': 'bel',
    'bel': 'bel',
    'be': 'bel',
    '白俄罗斯语': 'bel',
    'swahili': 'swa',
    'kiswahili': 'swa',
    'swa': 'swa',
    'sw': 'swa',
    '斯瓦希里语': 'swa',
    'uzbek': 'uzb',
    'uzb': 'uzb',
    'uz': 'uzb',
    '乌兹别克语': 'uzb',
    'sinhala': 'sin',
    'sinhalese': 'sin',
    'sin': 'sin',
    'si': 'sin',
    '僧伽罗语': 'sin',
    'marathi': 'mar',
    'mar': 'mar',
    'mr': 'mar',
    '马拉地语': 'mar',
    'gujarati': 'guj',
    'guj': 'guj',
    'gu': 'guj',
    '古吉拉特语': 'guj',
    'kurdish': 'kur',
    'kur': 'kur',
    'ku': 'kur',
    '库尔德语': 'kur',
    'amharic': 'amh',
    'amh': 'amh',
    'am': 'amh',
    '阿姆哈拉语': 'amh',
    'latin': 'lat',
    'lat': 'lat',
    'la': 'lat',
    '拉丁语': 'lat',
    'galician': 'glg',
    'glg': 'glg',
    'gl': 'glg',
    '加利西亚语': 'glg',
    'multi': 'mul',
    'mul': 'mul',
    '\u591a\u8bed\u8a00': 'mul',
    '\u591a\u79cd\u8bed\u8a00': 'mul',
  };

  static void mergeLanguageMap(Map<String, String> mapping) {
    for (final entry in mapping.entries) {
      final rawKey = entry.key.trim().toLowerCase();
      final value = _normalizeLanguageValue(entry.value);
      if (rawKey.isEmpty || value.isEmpty) continue;
      final key = normalizeLanguageCode(rawKey) ?? rawKey;
      _languageNameMap[key] = value;
      _languageAliasToCode.putIfAbsent(rawKey, () => key);
    }
  }

  static String _normalizeLanguageValue(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return '';
    if (value == '未确定的语言') return '';
    return value;
  }

  static String languageName(String raw) {
    final key = raw.trim().toLowerCase();
    if (key.isEmpty || key == 'zz-unknow' || key == 'unknown' || key == 'und') {
      return '';
    }
    final normalizedKey = normalizeLanguageCode(key);
    if (normalizedKey == null) return '';
    return _languageNameMap[normalizedKey] ?? _languageNameMap[key] ?? '';
  }

  static String subtitleLabel(String raw) {
    return languageName(raw);
  }

  static String? normalizeLanguageCode(String raw) {
    final key = raw.trim().toLowerCase();
    if (key.isEmpty || key == 'zz-unknow' || key == 'unknown' || key == 'und') {
      return null;
    }
    return _languageAliasToCode[key] ??
        (_languageNameMap.containsKey(key) ? key : null);
  }

  static String? inferLanguageCodeFromText(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return null;
    final normalizedCode = normalizeLanguageCode(value);
    if (normalizedCode != null) {
      return normalizedCode;
    }
    final lower = value.toLowerCase();
    final tokens = lower
        .split(RegExp(r'[^a-z0-9]+'))
        .where((token) => token.isNotEmpty)
        .toList(growable: false);
    for (final token in tokens) {
      final code = normalizeLanguageCode(token);
      if (code != null) {
        return code;
      }
    }
    for (final entry in _languageAliasToCode.entries) {
      final alias = entry.key;
      if (alias.codeUnits.any((unit) => unit > 127) && value.contains(alias)) {
        return entry.value;
      }
    }
    return null;
  }
}
